import React from 'react'
import Head from 'next/head'
import Main from './Main'
import SideBar from './SideBar'
import TopBar from './TopBar'

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Delivery Food</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <SideBar className="md:flex hidden lg:w-80 w-28 rounded-r-3xl" />
            <Main>
                <TopBar />
                {children}
            </Main>
        </>
    )
}

export default Layout
