import React, { useContext } from 'react'
import Head from 'next/head'
import Main from './Main'
import SideBar from './SideBar'
import TopBar from './TopBar'
import AuthRequired from '../gardians/AuthRequired'
import { AuthenticationContext } from '../../contexts'

const Layout = ({ children }) => {
    const currentUser = useContext(AuthenticationContext)
    return (
        <>
            < Head >
                <meta charset="utf-8" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Delivery Food</title>
            </Head >
            <AuthRequired>
                {
                    currentUser ?
                        <>
                            <SideBar className="md:flex hidden lg:w-80 w-28 rounded-r-3xl" />
                            <Main>
                                <TopBar />
                                {children}
                            </Main>
                        </>
                        :
                        children

                }

            </AuthRequired >
        </>

    )
}

export default Layout
