import '../styles/globals.css'
import React from 'react';
import Layout from '../components/layout/Layout'
import { AuthenticationProvider } from '../contexts/AuthenticationContext';
import Head from 'next/head';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient({
  //settings 
})

function MyApp({ Component, pageProps }) {
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Delivery Food</title>
      </Head>
      <AuthenticationProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </AuthenticationProvider>
    </QueryClientProvider>
  )
}

export default MyApp
