import '../styles/globals.css'

import React from 'react';
import Layout from '../components/layout/Layout'
import { AuthenticationProvider } from '../contexts/AuthenticationContext';

import { useRouter } from "next/router";
import Head from 'next/head';
function MyApp({ Component, pageProps }) {

  const router = useRouter()
  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Delivery Food</title>
      </Head>
      <AuthenticationProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </AuthenticationProvider>
    </>

  )
}

export default MyApp
